// Generates nodes/.../endpoints.ts from the API's openapi.json, then (after build) the
// "Node to API mapping" table in README.md. Run: npm run gen [path/to/openapi.json]
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const specPath = process.argv[2] ?? new URL('../../wp-rapidapi/openapi.json', import.meta.url);
const spec = JSON.parse(readFileSync(specPath, 'utf8'));

// 1. endpoints.ts: "METHOD /path" -> docs summary
const endpoints = {};
for (const [path, methods] of Object.entries(spec.paths))
	for (const [m, o] of Object.entries(methods)) if (o.summary) endpoints[`${m.toUpperCase()} ${path}`] = o.summary;
writeFileSync(
	new URL('../nodes/WhatsAppRetentionStack/endpoints.ts', import.meta.url),
	`// Generated by scripts/gen.mjs from openapi.json. Do not edit.\nexport const ENDPOINTS: Record<string, string> = ${JSON.stringify(endpoints, null, '\t')};\n`,
);
console.log(`endpoints.ts: ${Object.keys(endpoints).length} routes`);

// 2. README table from the built node
execSync('npm run build', { stdio: 'inherit' });
const require = createRequire(import.meta.url);
const { WhatsAppRetentionStack } = require('../dist/nodes/WhatsAppRetentionStack/WhatsAppRetentionStack.node.js');
const node = new WhatsAppRetentionStack().description;
const rows = [];
for (const p of node.properties.filter((p) => p.name === 'operation')) {
	const resource = p.displayOptions.show.resource[0];
	for (const o of p.options) rows.push(`| ${resource[0].toUpperCase() + resource.slice(1)} | ${o.name} | ${o.action} | \`${o.description}\` |`);
}
const table = ['| Resource | Operation | API docs name | Endpoint |', '|---|---|---|---|', ...rows].join('\n');
const readmePath = new URL('../README.md', import.meta.url);
const readme = readFileSync(readmePath, 'utf8');
const [start, end] = ['<!-- api-map:start -->', '<!-- api-map:end -->'];
if (!readme.includes(start)) throw new Error(`README.md needs ${start} and ${end} markers`);
writeFileSync(readmePath, readme.replace(new RegExp(`${start}[\\s\\S]*${end}`), `${start}\n${table}\n${end}`));
console.log(`README.md: ${rows.length} rows`);
